language: node_js
dist: trusty
node_js:
  - '12'
before_install: # if "install" is overridden
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules
install: yarn --frozen-lockfile --non-interactive || (echo 'package.json is not in sync with yarn.lock, check that you include yarn.lock' && false)
script:
  - yarn pretty-quick --check --verbose --branch origin/master &&
    yarn build:dev &&
    yarn test --forceExit --maxWorkers=4
env:
  global:
    - secure: aI1uMj0h6xjzp2Xl8VeG4Eibnmz77OaTs8vYyOwgf4L5eN59Rz21oJE4j4AFkDBELUJvYHJix/EKWoIGszDFN/XCoOcB39h9MFyrHT74dwmjH1CHDg97e8KZU8oKpvpJ6D5c1tYUrbuzeK+pxqGptMi3zi9Cx8UpN9CavVa1QkcfEf0VfVdGpHIf+EbP9imEnArfPkUMfx0Schp761gySOvgtzzjIUwFLrrszSWM5s5KA8Z2BWMKN4877uey2HCYqfju9TrjWv396QxWxdnzqGvTQCO5jabcxSuK3N5IC76mlkuT/w0rxHVwULDU9JyBQo6gYGkHavKq5vvTOrWzEZwhL5mY6RvCwPg4GJma+O6DWZQRLEbF18Ubu2pm8BbLp+EUdgQMN+rBhTcbhX/om+tZkyODoVmxSEibSo6LcDJ3ZiS8pzlFVQiUbQ3wiQqcIPoDwlhhahwUutd35zt26HJvSs4HuRZ1R6TU3xtsHFVQULbIOMWcWd5dFnzTdBJW3aNu45vkWOE7wtANiAKmpkFowq0lRoKj6GdHgDEk9L0xy/QmoiCmCnrqtSsIill0GjmPpXWzIBQmS4uPUkjGveIqIGfrRqnSyRa6+f0wY4GQ0vkbF4DFbCTvRVcfvvph2R3MS/Tjhvt5L5Bhw52lg/DiWib2Synle1WyIjhXTLk=
    - NODE_OPTIONS=--max_old_space_size=4096

# The channel name "chat.freenode.net#kiali" is encrypted to prevent IRC spam from forks
notifications:
  irc:
    channels:
      - secure: BqB/3O6bXEhLMTOSQhpBog1gaMJJscY3gKF1fwk3dIkoXTBQSRE0yjnSzcNXx2iswA600w94fM7y9YZxyIdEu/YuuPBisRKPEZKv63fRbeZdhW9BvtXwNzfdrr9CXdJwzaf5nruwxU6nRWe38D8ri3+A5OP0Oiy0vTKZmomXP/Re52OoqSLFR9hoS/EvsQphIpyBr/sZ6csw5r+KR7Ldkb6bwDkT4XrrsyGCNmxT2SZHv62qL82bYyH8MbUh3AkYOebvVYXwtfulBOs7m8KiqKfQBzQrZJQZXvcBvphwa2WYK0kFA9XUCwzc+kCKX2XtWzsmQfeDpxyYdXbYRB5QNSu1HhZsmGxxVQHIeSvZjOGCZq81wYm9bIMzxeOWhbZDJKvJFp6OHX6Nrq4GbYJzTUmNa6P77wFLl9e3haaIoJk4bfzYFuRcNn/uUJf9wrZTQdFSGSGbx8iMl8dimQCSCTi5ndi5Fn0H3S5plAjkeGk+KsqDwb6ibzNRjqzKt/UJvi318ezwhnN9Nptd3AT9JtEun13pu0PWPyYXiXBkeELKuK4RD1YoYL1hNTejp389tyPJygpCcYyhzqY6I+saYOAtCGwPhJjWydOBB7VRjyqoctHbjj20qwJychUOenVCRsxtnRhzv5nxM+QRbsN3STLkEsI/U8LN7s+6b6zyDlM=
    on_success: change
    on_failure: change
