# This is a basic workflow to help you get started with Actions

name: Kiali-UI CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies and verify lockfile
        # yarn install will update the yarn.lock file when it doesn't match the package.json.
        # This can happen when the lockfile has been updated but the package.json file was not.
        # The '--frozen-lockfile' flag ensures that the yarn.lock file remains the same after yarn install.
        run: yarn install --frozen-lockfile
      - run: yarn pretty-quick --check --verbose --branch origin/master
      - run: yarn build:dev
      - run: yarn test
